#=============================================================================
#
#-- Author: P Campbell-Burns, UKMON
#
#
#-- Description:
#
#   This script generates a summary report for each of a defined list of U
#    UKMON station.  The reports theselves are generated by a call to
#   markdown file STATION_SUMMARY_KNITR.RMD.
#
#-- Shared under the Creative Common  Non Commercial Sharealike 
#   License V4.0 (www.creativecommons.org/licebses/by-nc-sa/4.0/)
#
#-- Version history
#
#   Vers  Date          Notes
#   ----  ----          -----
#   1.1   09/02/2016    Moved root path from config file to improve MacOS compatibility
#   1.0   19/01/2016    First release
#
#=============================================================================

# Set report selection criteria

CurrentYr = '2016'
knitr::opts_chunk$set(echo = TRUE)

# Station list

stations <- list(
  "Almira",          c("Almira_Obs_AO"),
  "Ash",             c("Ash_Vale_K1", "Ash_Vale_K2", "Ash_Vale_K3"),
  "Church Crookham", c("Church_Cro_S1"), 
  "Clanfield",       c("Clanfield_NE", "Clanfield_NO", "Clanfield_SO"),
  "DL",              c("DL1_"),
  "Dorchester",      c("DORCHESTER_1"),
  "Duffryn",         c("Duffryn_C2"),
  "Horley",          c("Horley_SE"), 
  "Lockyer",         c("Lockyer_L1", "Lockyer1_L1", "Lockyer2_L2"),
  "MC",              c("MC1_c1"),
  "SCOTCH ST",       c("Scotch_St_C1", "Scotch_St_C2", "Scotch_St_C3"),
  "WILCOT",          c("Wilcot_", "Wilcot_01", "Wilcot_E", "Wilcot_NE", "Wilcot_NW", "Wilcot_SE", "Wilcot_SW", "Wilcot_W")
)

library(xtable)
library(knitr)
library(tcltk)


#-- Filesystem parameters

root = "~/ANALYSIS"					 # Filesystem root (~ is users documents folder on Windows)
source(paste(root, "/CONFIG/Lib_Config.r",sep=""))

read_ufo <- function(mx) {
  #===============================================================================
  #
  #-- Presents file picker filtered for CSV files (if no preconfigured input file)
  #-- Ingests file
  #-- Standardises data
  #
  #===============================================================================
  
  # - Read UFO Orbit data file
  
  # setup filter
  filt <- matrix(c("Comma separated / Excel files","*.csv"), 
                 nrow = 1, ncol = 2, byrow = TRUE,
                 dimnames = list(c("csv"),c("V1","V2")))
  
  if (is.na(SourceUnified)) {
    infile <- tk_choose.files(caption = "Select UFO Orbit Unified file",multi = FALSE,filters=filt)
  } else {
    infile <- paste(DataDir,SourceUnified,sep="/")
  }
  
  if (infile == "") stop
  
  # --- Read the UFO data file
  
  # Read raw data
  mt <- read.csv(infile, header=TRUE)
  
  # Standardise ID1
  mt$X_ID1<- substring(mt$X_ID1,2)
  
  # standardise localtime
  mt$X_localtime <- as.POSIXct(strptime(mt$X_localtime, "_%Y%m%d_%H%M%S"))
  
  # remove NA localtimes if any
  mt <- subset(mt, ! is.na(X_localtime))
  
  # Standardise streamname
  mt$X_stream <- toupper(ifelse(substring(mt$X_stream,1,2)=="_J",substring(mt$X_stream,5),substring(mt$X_stream,2)))
  
  return (mt)
  }
  
  runtime = format(Sys.time(),"%Y%m%d_%H%M")
  
  # Import data
  
  mt <- read_ufo()
  
  
  # Datacleansing (resolve known issues in source data)
  if (is.factor(mt$X_amag)) {
    cat("Note: Problem detected in input data - amag converted from factor to numeric \n      Ignore next cooercion warnings")
    mt$X_amag <- as.numeric(as.character(mt$X_amag))
    mt <- mt[!is.na(mt$X_amag),]
  }
  
  if (is.factor(mt$X_QA)) {
    cat("Note: Problem detected in input data - QA converted from factor to numeric")
    mt$X_QA <- as.numeric(as.character(mt$X_QA))
    mt <- mt[!is.na(mt$X_QA),]
  }
  
  # Count rows imported
  
  rows_read <- nrow(mt)
  if (rows_read == 0) {
    stop("No data in input file")
  } 
  
  loop_max = length(stations) / 2
  assign("stations",stations, envir=knitrenv)
  assign("CurrentYr",CurrentYr, envir=knitrenv)
  knitrenv <- new.env()
  
  # For each station in the list, print report
  
  for (i in 1:loop_max) {
    idx = 2 * i - 1
    
    # Get station name
    SelectStation  = stations[idx]
    
    ms <- NA
    
    # Get data for all cameras operated by this staio
    ms <- subset(mt, X_ID1 %in% unlist(stations[idx+1]))
    assign("ms",ms, envir=knitrenv )    
    
    # Skip report if no data
    if (nrow(ms) != 0) {
      
     # Get observationf for station for the feature year
     my <- ms[substr(ms$X_localtime,1,4)==CurrentYr,]
     assign("SelectStation",SelectStation, envir=knitrenv )
     assign("my",my, envir=knitrenv ) 
     
     # Skip report if no data for the year
     if (nrow(my) != 0) {
       
       # Produce report
       
        rmarkdown::render(paste(root,'/STATION_SUMMARY_KNITR.rmd',sep=""),envir=knitrenv,output_dir=ReportDir, output_file=paste(SelectStation,".html",sep="")) 
        }
    }
  }
  
  