#!/usr/bin/Rscript
#=============================================================================
#
#-- Author: P Campbell-Burns, UKMON
#
#
#-- Description:
#
#   This script generates a summary report for each of a defined list of U
#    UKMON station.  The reports theselves are generated by a call to
#   markdown file STATION_SUMMARY_KNITR.RMD.
#
#-- Shared under the Creative Common  Non Commercial Sharealike
#   License V4.0 (www.creativecommons.org/licebses/by-nc-sa/4.0/)
#
#-- Version history
#
#   Vers  Date          Notes
#   ----  ----          -----
#   1.2   14/03/2017    Ingest UNIFIED as well as singletons to report on matches
#   1.1   09/02/2017    Moved root path from config file to improve MacOS compatibility
#   1.0   19/01/201y    First release
#
#=============================================================================

# Set report selection criteria
args = commandArgs(trailingOnly = TRUE)
if (length(args) == 0) {
  Ylist = c("2017","2018","2019","2020","2021","2022")
  i <- menu(Ylist, graphics = TRUE, title = "Choose year")
  CurrentYr = strtoi(Ylist[i])
}else{
  CurrentYr = strtoi(args[1])  
}


source(paste(".", "CONFIG/Lib_Config.r",sep="/"))

knitr::opts_chunk$set(echo = TRUE)

# Station list
source(paste(RefDir,"StationList.r", sep="/"))

library(xtable)
library(knitr)
library(tcltk)
library(stringr)

#-- Filesystem parameters


  runtime = format(Sys.time(),"%Y%m%d_%H%M")

  # Import data

#  SourceUnified    <-  "UKMON-all-unified.csv"   # Unified Obs File
#  SourceSingle     <-  "UFO_Merged_Files.csv"       # Single Obs File

  # - Read UFO Orbit data file

  #indir <- tk_choose.dir(caption = "Select source directory")
  #infile1 <- paste(indir,"/",SourceUnified,sep = "")
  #infile2 <- paste(indir,"/",SourceSingle,sep = "")
  infile1 <- paste(DataDir, SourceUnified, sep = "/")
  infile2 <- paste(DataDir, SourceSingle, sep = "/")

  # --- Read the UFO data filea
  m_all_unified <- read.csv(infile1, header=TRUE)
  m_all_single <- read.csv(infile2, header=TRUE)

  # Standardise UNIFIED data
  m_all_unified$X_ID1<- substring(m_all_unified$X_ID1,2)
  m_all_unified$X_localtime <- as.POSIXct(strptime(m_all_unified$X_localtime, "_%Y%m%d_%H%M%S"))
  m_all_unified  <- subset(m_all_unified, ! is.na(X_localtime))
  m_all_unified$X_stream <- toupper(ifelse(substring(m_all_unified$X_stream,1,2)=="_J",substring(m_all_unified$X_stream,5),substring(m_all_unified$X_stream,2)))

  # Standardise SINGLETON data
  trim_J <- function (x) gsub("^J\\d_|^\\sJ\\d_|\\s", "", x)
  m_all_single <-   m_all_single[grep("^J\\d_|^\\sJ\\d_|SPO|\\sSPO|spo|\\sspo",m_all_single$Group),]
  m_all_single$X_ID1<- str_trim(m_all_single$Loc_Cam)
  m_all_single$X_localtime <- as.POSIXct(strptime(m_all_single$LocalTime, "%Y%m%d_%H%M%S"))
  m_all_single <- subset(m_all_single, ! is.na(LocalTime))
  m_all_single$X_stream <- toupper(trim_J(m_all_single$Group))
  m_all_single$X_mag <- as.numeric(trim_J(m_all_single$Mag))
  m_all_single$X_dur <- toupper(trim_J(m_all_single$Dur.sec.))
  m_all_single  <- subset(m_all_single, ! is.na(X_localtime))
  m_all_single <- subset(m_all_single, m_all_single$X_stream != 'TBC')


  m_all_single <- m_all_single[,c("X_ID1", "X_stream", "X_localtime", "X_dur", "X_mag")]
  m_all_unified <- m_all_unified[,c("X_ID1", "X_ID2", "X_stream","X_localtime", "X_dur", "X_mag")]

  if (nrow(m_all_single) == 0) {
    stop("No data in input file")
  }

  # Count rows imported

  loop_max = length(stations) / 2
  knitrenv <- new.env()

  assign("stations",      stations,      envir=knitrenv)
  assign("CurrentYr",     CurrentYr,     envir=knitrenv)

  # For each station in the list, print report

  for (i in 1:loop_max) {
    idx = 2 * i - 1

    # Get station name
    SelectStation  = stations[idx]

    m_s_station_all <- NA
    m_u_station_all <- NA

    # Get data for all cameras operated by this staio
    m_s_station_all  <- subset(m_all_single,  X_ID1 %in% unlist(stations[idx+1]))
    m_u_station_all  <- subset(m_all_unified, X_ID1 %in% unlist(stations[idx+1]))

    assign("m_s_station_all", m_s_station_all,envir=knitrenv )
    assign("m_u_station_all", m_u_station_all, envir=knitrenv )

    # Skip report if no data
    if (nrow(m_s_station_all) != 0 ) {

      assign("SelectStation",SelectStation, envir=knitrenv )

      m_s_station_yr <- m_s_station_all[substr(m_s_station_all$X_localtime,1,4)==CurrentYr,]
      m_u_station_yr <- m_u_station_all[substr(m_u_station_all$X_localtime,1,4)==CurrentYr,]

      assign("m_s_station_yr",m_s_station_yr, envir=knitrenv )
      assign("m_u_station_yr",m_u_station_yr, envir=knitrenv )

    # Skip report if no data for the year
    if (nrow(m_s_station_yr) != 0) {

    # Produce report
       outdir = paste(ReportDir, "stations", CurrentYr, sep="/")
       rmarkdown::render(paste(root,'/STATION_SUMMARY_KNITR.rmd',sep=""),envir=knitrenv,output_dir=outdir, output_file=paste(SelectStation,".html",sep=""))
        }
    }
  }

  